#   __________                                .__     .___                                ___________.__                       _____                     .___                
#   \______   \_____    __ __   ______  ____  |__|  __| _/  ____    ____      ___  ___    \__    ___/|  |__    ____    ____  _/ ____\  ____    ____    __| _/  ____  _______ 
#    |     ___/\__  \  |  |  \ /  ___/_/ __ \ |  | / __ |  /  _ \  /    \     \  \/  /      |    |   |  |  \ _/ __ \  /  _ \ \   __\ _/ __ \  /    \  / __ | _/ __ \ \_  __ \
#    |    |     / __ \_|  |  / \___ \ \  ___/ |  |/ /_/ | (  <_> )|   |  \     >    <       |    |   |   Y  \\  ___/ (  <_> ) |  |   \  ___/ |   |  \/ /_/ | \  ___/  |  | \/
#    |____|    (____  /|____/ /____  > \___  >|__|\____ |  \____/ |___|  /    /__/\_ \      |____|   |___|  / \___  > \____/  |__|    \___  >|___|  /\____ |  \___  > |__|   
#                   \/             \/      \/          \/              \/           \/                    \/      \/                      \/      \/      \/      \/       

#Copyright Paul-Theodor.de to Present
#All rights reserved.

Prefix: '§7§l[§a§lTeamChat§7§l]'
SendPermission: 'teamchat.send'
SeePermission: 'teamchat.see'
NameColor: '§4' 
MessageColor: '§f'
NoMessageAfterCommand: 'Syntax: /tc [Message]'
CommandAlias: 'teamc'






#________                      ______________        _____ 
#___  __/__________ _______ _____  ____/__  /_______ __  /_
#__  /  _  _ \  __ `/_  __ `__ \  /    __  __ \  __ `/  __/
#_  /   /  __/ /_/ /_  / / / / / /___  _  / / / /_/ // /_  
#/_/    \___/\__,_/ /_/ /_/ /_/\____/  /_/ /_/\__,_/ \__/ 